version: "3"

services:
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: medAdmin
      ME_CONFIG_BASICAUTH_PASSWORD: medAdmin123
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: "mongodb://admin:admin@localhost:27017/"
    links:
      - mongo
    networks:
      - mongo-compose-network
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: ms-med-express
    ports:
      - "27017:27017"
    volumes:
      - ./.volumes/:/data/db
    networks:
      - mongo-compose-network
networks:
  mongo-compose-network:
    driver: bridge